language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI = true
deploy:
  provider: heroku
  api_key:
    secure: EUO0U4WkBxIJdanAucUE5sWMlPm09QJhLYggi/ndTt2fTV7Eb9PP3RLsGunuxMN5gYwIdkUnIvb1NLluX/kVN+F/MZza8oTBpxLsPSSTSUQeRhNW3AyxMWbtuDt7Extnnzaxptpd2vqHfnewcXVeawbukhodQus4JTa4UaUPSgmenABKSfn4nXnkVbCLpBTnaKpqKkk7pU+wmRNYumO8IwIut8SoRMDKLrAKPAib5LyYomY33Q5PGHlz+mtFhmjWl26ij4h4NLQsAGwIDdvPVOkkFpdSs6W+xbWf5rHtv5AE6MgcBCUYtBjhsl1EVR3HjoGXrzHPZmS0G0CfPr+b43WjqwdMsGKQjuFnaTsbygid+enNtWYH6BxTuGc2sESJGxZLKqx3+mtOxHyYbNhsYzfCGvGXzg0inFf69/c4sExoCZr434kO+PdhZ3oF78n4xsN8CB5UTdLvJtTXHQq0eCIxX2JxvaOGNG1cy5gzf1A9jA/9TMklNCFyDCEJSVh8hCNZ/nKp85xiAKXGgVBNKFA42RdZy5DvtkJHtlu/DWja8qvJjCMNTdO+yTx/kB6zzNaHhoVS5MaL/W8SIBdNCBfW85uz9hsQvVrvBSTYKknayx/EbE/mJXa21gDU5VqIxXlVkEVjk2Cti4OUklpElwzUmK3B85FVbOnxYaxm/2M=
  app: calm-savannah-27155
  on:
    repo: ispoljari/react-recipe-builder-app
  branches:
    only:
      - master